version: '2'
networks:
    cluster:
        driver: bridge

volumes:
    pgmaster:
    pgslave1:
    pgslave2:
    backup:

services:
    pgmaster:
        build:
            context: ../src
            dockerfile: Postgres-10-Repmgr-3.2.Dockerfile
        environment:
            NODE_ID: 1 # Integer number of node (not required if can be extracted from NODE_NAME var, e.g. node-45 => 1045)
            NODE_NAME: node1 # Node name
            CLUSTER_NODE_NETWORK_NAME: pgmaster # (default: hostname of the node)
            
            PARTNER_NODES: "pgmaster,pgslave1"
            REPLICATION_PRIMARY_HOST: pgmaster # That should be ignored on the same node
            
            NODE_PRIORITY: 100  # (default: 100)
            SSH_ENABLE: 1
            #database we want to use for application
            POSTGRES_PASSWORD: root
            POSTGRES_USER: root
            POSTGRES_DB: main_db
            CLEAN_OVER_REWIND: 0
            CONFIGS_DELIMITER_SYMBOL: ;
            CONFIGS: "listen_addresses:'*';max_replication_slots:5"
                                  # in format variable1:value1[,variable2:value2[,...]] if CONFIGS_DELIMITER_SYMBOL=, and CONFIGS_ASSIGNMENT_SYMBOL=:
                                  # used for pgpool.conf file
            #defaults:
            CLUSTER_NAME: pg_cluster # default is pg_cluster
            REPLICATION_DB: replication_db # default is replication_db
            REPLICATION_USER: replication_user # default is replication_user
            REPLICATION_PASSWORD: replication_pass # default is replication_pass
            
        ports:
            - 9900:5432
        volumes:
            - pgmaster:/var/lib/postgresql/data
        networks:
            cluster:
                aliases:
                    - pgmaster
    pgslave1:
        build:
            context: ../src
            dockerfile: Postgres-10-Repmgr-3.2.Dockerfile
        environment:
            NODE_ID: 2
            NODE_NAME: node2
            CLUSTER_NODE_NETWORK_NAME: pgslave1 # (default: hostname of the node)
            
            PARTNER_NODES: "pgmaster,pgslave1"
            REPLICATION_PRIMARY_HOST: pgmaster
            CLEAN_OVER_REWIND: 1
            CONFIGS_DELIMITER_SYMBOL: ;
            CONFIGS: "max_replication_slots:10" #some overrides
        ports:
            - 5441:5432
        volumes:
            - pgslave1:/var/lib/postgresql/data
        networks:
            cluster:
                aliases:
                    - pgslave1

    # Add more slaves if required
    pgslave2:
        build:
            context: ../src
            dockerfile: Postgres-10-Repmgr-3.2.Dockerfile
        environment:
            NODE_ID: 3
            NODE_NAME: node3
            CLUSTER_NODE_NETWORK_NAME: pgslave2 # (default: hostname of the node)

            REPLICATION_PRIMARY_HOST: pgslave1 # I want to have cascade Streeming replication
            #USE_REPLICATION_SLOTS: 0
            CONFIGS_DELIMITER_SYMBOL: ;
            CONFIGS: "listen_addresses:'*'"
        ports:
            - 5442:5432
        volumes:
            - pgslave2:/var/lib/postgresql/data
        networks:
            cluster:
                aliases:
                    - pgslave2
    backup:
        build:
            context: ../src
            dockerfile: Barman-2.3-Postgres-10.Dockerfile
        environment:
            REPLICATION_USER: replication_user # default is replication_user
            REPLICATION_PASSWORD: replication_pass # default is replication_pass
            REPLICATION_HOST: pgmaster
            POSTGRES_PASSWORD: root
            POSTGRES_USER: root
            POSTGRES_DB: main_db
            SSH_ENABLE: 1
            BACKUP_SCHEDULE: "*/30 */5 * * *"
        volumes:
            - backup:/var/backups
        networks:
            cluster:
                aliases:
                    - backup
    pgpool:
        build:
            context: ../src
            dockerfile: Pgpool-3.7-Postgres-10.Dockerfile
        environment:
            PCP_USER: pcp_user
            PCP_PASSWORD: pcp_pass
            WAIT_BACKEND_TIMEOUT: 60

            CHECK_USER: root
            CHECK_PASSWORD: root
            CHECK_PGCONNECT_TIMEOUT: 3 #timout for checking if primary node is healthy
            SSH_ENABLE: 1
            DB_USERS: root:root # in format user:password[,user:password[...]]
            BACKENDS: "0:pgmaster:5432:1:/var/lib/postgresql/data:ALLOW_TO_FAILOVER,1:pgslave1::::,2:pgslave2::::"
            REQUIRE_MIN_BACKENDS: 2 # minimal number of backends to start pgpool (some might be unreachable)
            CONFIGS: "num_init_children:250,max_pool:4"
                      # in format variable1:value1[,variable2:value2[,...]] if CONFIGS_DELIMITER_SYMBOL=, and CONFIGS_ASSIGNMENT_SYMBOL=:
                      # used for pgpool.conf file
        ports:
            - 5430:5432
            - 9898:9898 # PCP
        networks:
            cluster:
                aliases:
                    - pgpool
##
#    postgres_conf:
#        build:
#          context: ../src/
#          dockerfile: Postgres-10-Repmgr-3.2.Dockerfile
#        environment:
#          NODE_NAME: node-102 # Node name
#          CLUSTER_NODE_NETWORK_NAME: postgres_conf # (default: hostname of the node)
#          POSTGRES_PASSWORD: root
#          POSTGRES_USER: root
#          POSTGRES_DB: main_db
#          CLEAN_OVER_REWIND: 0
#          CONFIGS: "listen_addresses)'some_host'|max_replication_slots)55"
#          CONFIGS_DELIMITER_SYMBOL: "|"
#          CONFIGS_ASSIGNMENT_SYMBOL: ")"
#    pgpool_conf:
#        build:
#            context: ../src
#            dockerfile: Pgpool-3.7-Postgres-10.Dockerfile
#        environment:
#            PCP_USER: pcp_user
#            PCP_PASSWORD: pcp_pass
#
#            CHECK_USER: root
#            CHECK_PASSWORD: root
#
#            CHECK_PGCONNECT_TIMEOUT: 3 #timout for checking if primary node is healthy
#            DB_USERS: root:root # in format user:password[,user:password[...]]
#            CONFIGS: "num_init_children)12|max_pool)13"
#            CONFIGS_DELIMITER_SYMBOL: "|"
#            CONFIGS_ASSIGNMENT_SYMBOL: ")"
#        ports:
#            - 5440:5432
#            - 9897:9898 # PCP